version: '3.8'
services:
    lar_nginx:
        image: nginx:alpine
        container_name: lar_nginx
        volumes:
            - '.:/var/www/html/cmsqdjr'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
            - './docker/nginx/logs:/var/log/nginx'
        expose:
            - 80
            - 443
        dns:
            - 8.8.8.8
            - 4.4.4.4
        network_mode: "host"

    lar_php84:
        image: quocdaijr/php-fpm:8.4
        container_name: lar_php84
        working_dir: /var/www/html/cmsqdjr
        volumes:
            - '.:/var/www/html/cmsqdjr'
            - './docker/php84/supervisor/conf.d:/etc/supervisor/conf.d'
            - './docker/php84/supervisor/logs:/var/log/cache'
            - './docker/php84/php-fpm/conf.d/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
        expose:
            - 9000
        dns:
            - 8.8.8.8
            - 4.4.4.4
        network_mode: "host"

#    lar_rabbitmq:
#        image: quocdaijr/rabbitmq:3.8.19
#        container_name: lar_rabbitmq
#        volumes:
#            - './docker/rabbitmq/logs:/var/log/rabbitmq/log'
#        environment:
#            RABBITMQ_DEFAULT_USER: admin
#            RABBITMQ_DEFAULT_PASS: 12345@
#        expose:
#            - 15672
#            - 5672
#        dns:
#            - 8.8.8.8
#            - 4.4.4.4
#        network_mode: "host"

    lar_mysql:
        image: quocdaijr/msql:8.0
        container_name: lar_mysql
        volumes:
            - './docker/mysql/data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=12345@
            - MYSQL_DATABASE=cmsqdjr
            - MYSQL_USER=basic-user
            - MYSQL_PASSWORD=basic-password
        expose:
            - 3306
        dns:
            - 8.8.8.8
            - 4.4.4.4
        network_mode: "host"

#    lar_elasticsearch7:
#        image: quocdaijr/elasticsearch:7.12.1
#        container_name: lar_elasticsearch7
#        volumes:
#            - ./docker/elasticsearch7/data:/usr/share/elasticsearch/data
#        environment:
#            - discovery.type=single-node
#        #      - ELASTICSEARCH_HEAP_SIZE=1g
#        expose:
#            - 9200
#            - 9300
#        dns:
#            - 8.8.8.8
#            - 4.4.4.4
#        network_mode: "host"

    lar_redis:
        image: redis:7.2-alpine
        container_name: lar_redis
        volumes:
            - './docker/redis/data:/data'
        expose:
            - 6379
        dns:
            - 8.8.8.8
            - 4.4.4.4
        network_mode: "host"
